[package]
name = "project_infra"
version = "0.1.0"
edition = "2021"

[dependencies]
project_domain.workspace = true

tokio.workspace = true
thiserror.workspace = true
async-trait.workspace = true
dotenvy.workspace = true
tempfile.workspace = true
