[package]
name = "project-infra"
version = "0.1.0"
edition = "2021"

[dependencies]
project-domain.workspace = true

tokio.workspace = true
thiserror.workspace = true
async-trait.workspace = true
dotenvy.workspace = true
tempfile.workspace = true
